version: "3.3"
services:
  mpd:
    build:
      context: ./mpd
      dockerfile: Dockerfile
    ports:
    - "6600:6600"
    volumes:
    - ./env/mpd_mount/music:/mpd/music
    - ./env/mpd_mount/logs:/mpd/logs
    restart: on-failure
  elasticsearch:
    image: elasticsearch:5-alpine
    restart: on-failure
  mpd_indexer:
    build:
      context: ./mpd_indexer
      dockerfile: Dockerfile
    links:
    - "mpd:mpd"
    - "elasticsearch:elasticsearch"
    volumes:
    - ./env/mpd_mount/logs:/mpd/logs
    command:
    - "-logfile"
    - "/mpd/logs/log"
    - "-mpdurl"
    - "mpd:6600"
    - "-esurl"
    - "http://elasticsearch:9200"
    restart: on-failure
  api_server:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    links:
    - "mpd:mpd"
    - "elasticsearch:elasticsearch"
    command:
    - "-listenurl"
    - "0.0.0.0:3000"
    - "-mpdurl"
    - "mpd:6600"
    - "-esurl"
    - "http://elasticsearch:9200"
    restart: on-failure
  mpd_ui:
    build:
      context: ./mpd_ui
      dockerfile: Dockerfile
    links:
    - "mpd:mpd"
    - "api_server:api_server"
    restart: on-failure
    ports:
    - "8080:8080"
