version: "3.3"
services:
  mpd:
    build:
      context: ./mpd
      dockerfile: Dockerfile
    ports:
    - "6600:6600"
    - "8000:8000"
    volumes:
    - ./env/mpd_mount/music:/mpd/music
    - ./env/mpd_mount/logs:/mpd/logs
    - ./env/mpd_mount/socket:/mpd/socket
    restart: on-failure
  elasticsearch:
    image: elasticsearch:5-alpine
    restart: on-failure
    ports:
    - "9200:9200"
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    links:
    - "mpd:mpd"
    - "elasticsearch:elasticsearch"
    volumes:
    - ./env/mpd_mount/logs:/mpd/logs
    - ./env/mpd_mount/socket:/mpd/socket
    command:
    - "-listenurl"
    - "0.0.0.0:3000"
    - "-logfile"
    - "/mpd/logs/log"
    - "-mpdsocket"
    - "/mpd/socket/mpd.sock"
    - "-esurl"
    - "http://elasticsearch:9200"
    restart: on-failure